### ISSUE TITLE
Undefined function 'Kors'

### ISSUE THREAD

**Issue by paul-md** [Tereshchenkolab/Global-Electrical-Heterogeneity#2]
Dear Larisa,

I get the following error in MatLab when running Kors_git.m "Undefined function 'kors' for input arguments of type 'double'." at the following line "XYZ_O=kors(ECG12Lead);"

What can I do to make it work?
Thank you!

**Comment by AnnaPersh** [comment]
Hi! 

The function "kors" is defined on line 58 and on of "Kors_git.m". The input of kors function is a M x 12 matrix, where M is the length of the recording time. Have you tried to download the whole file from the repository and test it on the test 12LECG.mat file?

Thank you,
Annabel
